spring.application.name=ms-api-gateway
server.port=8080

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8090/realms/neobank

management.endpoints.web.exposure.include=*
management.endpoint.health.probes.enabled=true

springdoc.swagger-ui.urls[0].name=user-service
springdoc.swagger-ui.urls[0].url=/api-docs/user-service

springdoc.swagger-ui.urls[1].name=account-service
springdoc.swagger-ui.urls[1].url=/api-docs/account-service

springdoc.swagger-ui.urls[2].name=card-service
springdoc.swagger-ui.urls[2].url=/api-docs/card-service

springdoc.swagger-ui.urls[3].name=transaction-service
springdoc.swagger-ui.urls[3].url=/api-docs/transaction-service

springdoc.swagger-ui.urls[4].name=admin-service
springdoc.swagger-ui.urls[4].url=/api-docs/admin-service

springdoc.swagger-ui.urls[5].name=notification-service
springdoc.swagger-ui.urls[5].url=/api-docs/notification-service

spring.cloud.gateway.mvc.routes[0].id=user-auth
spring.cloud.gateway.mvc.routes[0].uri=lb://user-service
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.mvc.routes[1].id=user-service
spring.cloud.gateway.mvc.routes[1].uri=lb://user-service
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/users/**

spring.cloud.gateway.mvc.routes[2].id=account-service
spring.cloud.gateway.mvc.routes[2].uri=lb://account-service
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/accounts/**

spring.cloud.gateway.mvc.routes[3].id=card-service
spring.cloud.gateway.mvc.routes[3].uri=lb://card-service
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/cards/**

spring.cloud.gateway.mvc.routes[4].id=transaction-service
spring.cloud.gateway.mvc.routes[4].uri=lb://transaction-service
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/transactions/**

spring.cloud.gateway.mvc.routes[5].id=admin-service
spring.cloud.gateway.mvc.routes[5].uri=lb://admin-service
spring.cloud.gateway.mvc.routes[5].predicates[0]=Path=/api/admin/**
spring.cloud.gateway.mvc.routes[5].filters[0]=AddRequestHeader=X-Admin-Request, true

spring.cloud.gateway.mvc.routes[6].id=notification-service
spring.cloud.gateway.mvc.routes[6].uri=lb://notification-service
spring.cloud.gateway.mvc.routes[6].predicates[0]=Path=/api/notifications/**

spring.cloud.gateway.mvc.routes[7].id=user-service-docs
spring.cloud.gateway.mvc.routes[7].uri=lb://user-service
spring.cloud.gateway.mvc.routes[7].predicates[0]=Path=/api-docs/user-service
spring.cloud.gateway.mvc.routes[7].filters[0]=SetPath=/v3/api-docs

spring.cloud.gateway.mvc.routes[8].id=account-service-docs
spring.cloud.gateway.mvc.routes[8].uri=lb://account-service
spring.cloud.gateway.mvc.routes[8].predicates[0]=Path=/api-docs/account-service
spring.cloud.gateway.mvc.routes[8].filters[0]=SetPath=/v3/api-docs

spring.cloud.gateway.mvc.routes[9].id=card-service-docs
spring.cloud.gateway.mvc.routes[9].uri=lb://card-service
spring.cloud.gateway.mvc.routes[9].predicates[0]=Path=/api-docs/card-service
spring.cloud.gateway.mvc.routes[9].filters[0]=SetPath=/v3/api-docs

spring.cloud.gateway.mvc.routes[10].id=transaction-service-docs
spring.cloud.gateway.mvc.routes[10].uri=lb://transaction-service
spring.cloud.gateway.mvc.routes[10].predicates[0]=Path=/api-docs/transaction-service
spring.cloud.gateway.mvc.routes[10].filters[0]=SetPath=/v3/api-docs

spring.cloud.gateway.mvc.routes[11].id=admin-service-docs
spring.cloud.gateway.mvc.routes[11].uri=lb://admin-service
spring.cloud.gateway.mvc.routes[11].predicates[0]=Path=/api-docs/admin-service
spring.cloud.gateway.mvc.routes[11].filters[0]=SetPath=/v3/api-docs

spring.cloud.gateway.mvc.routes[12].id=notification-service-docs
spring.cloud.gateway.mvc.routes[12].uri=lb://notification-service
spring.cloud.gateway.mvc.routes[12].predicates[0]=Path=/api-docs/notification-service
spring.cloud.gateway.mvc.routes[12].filters[0]=SetPath=/v3/api-docs

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/


management.tracing.enabled=true
